/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LibraryRouteImport } from "./routes/library"
import { Route as GenerateRouteImport } from "./routes/generate"
import { Route as AuthRouteImport } from "./routes/auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as StorySlugRouteImport } from "./routes/story/$slug"

const LibraryRoute = LibraryRouteImport.update({
  id: "/library",
  path: "/library",
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: "/generate",
  path: "/generate",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: "/story/$slug",
  path: "/story/$slug",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/generate": typeof GenerateRoute
  "/library": typeof LibraryRoute
  "/story/$slug": typeof StorySlugRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/generate": typeof GenerateRoute
  "/library": typeof LibraryRoute
  "/story/$slug": typeof StorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/generate": typeof GenerateRoute
  "/library": typeof LibraryRoute
  "/story/$slug": typeof StorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/auth" | "/generate" | "/library" | "/story/$slug"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/auth" | "/generate" | "/library" | "/story/$slug"
  id: "__root__" | "/" | "/auth" | "/generate" | "/library" | "/story/$slug"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GenerateRoute: typeof GenerateRoute
  LibraryRoute: typeof LibraryRoute
  StorySlugRoute: typeof StorySlugRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/library": {
      id: "/library"
      path: "/library"
      fullPath: "/library"
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/generate": {
      id: "/generate"
      path: "/generate"
      fullPath: "/generate"
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/story/$slug": {
      id: "/story/$slug"
      path: "/story/$slug"
      fullPath: "/story/$slug"
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GenerateRoute: GenerateRoute,
  LibraryRoute: LibraryRoute,
  StorySlugRoute: StorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
