import { useRef } from "react"
import { createFileRoute } from "@tanstack/react-router"
import { motion } from "framer-motion"
import { ThemeAmbient } from "~/components/layout/ThemeAmbient"
import { PromptForm } from "~/components/prompt/PromptForm"
import { AppNav } from "~/components/layout/AppNav"
import { AppBrand, AppTagline } from "~/components/shared/AppBrand"
import { LandingHero } from "~/components/landing/LandingHero"
import { LandingFeatures } from "~/components/landing/LandingFeatures"
import { LandingMarquee, LandingCTA } from "~/components/landing/LandingMarquee"

export const Route = createFileRoute("/")({
  component: HomePage,
})

function HomePage() {
  const formRef = useRef<HTMLElement>(null)

  function scrollToForm() {
    formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })
  }

  return (
    <div className="relative">
      <div className="ambient-layer" aria-hidden>
        <ThemeAmbient />
      </div>

      <div className="relative z-10">
      <AppNav />

      <LandingHero onScrollToForm={scrollToForm} />

      <LandingMarquee />

      <LandingFeatures />

      {/* Prompt form section */}
      <section
        id="generate"
        ref={formRef}
        className="relative px-4 py-24 sm:py-32 scroll-mt-24"
      >
        <div className="max-w-2xl mx-auto">
          <LandingCTA />

          <motion.div
            className="surface p-6 sm:p-8 shadow-card relative overflow-hidden"
            initial={{ opacity: 0, y: 32 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-60px" }}
            transition={{ duration: 0.7, ease: "easeOut" }}
          >
            {/* Subtle inner glow */}
            <div
              className="absolute -top-24 left-1/2 -translate-x-1/2 w-64 h-64 rounded-full pointer-events-none opacity-30 blur-3xl"
              style={{ background: "radial-gradient(circle, rgba(220,38,38,0.15) 0%, transparent 70%)" }}
            />
            <div className="relative">
              <PromptForm />
            </div>
          </motion.div>

          <motion.p
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3 }}
            className="mt-8 text-center text-xs text-muted leading-relaxed"
          >
            Horror content generated by AI · Not suitable for all audiences ·{" "}
            <span className="text-night-500">Stories are saved to your library</span>
          </motion.p>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative px-4 py-10 border-t border-[var(--border)]">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="font-serif text-sm text-muted italic">
            <AppBrand /> — <AppTagline />
          </p>
          <p className="text-[10px] text-muted/60 font-mono uppercase tracking-widest">
            AI-generated fiction · 16+
          </p>
        </div>
      </footer>
      </div>
    </div>
  )
}
