import { useRef } from "react"
import { createFileRoute } from "@tanstack/react-router"
import { motion } from "framer-motion"
import { ThemeAmbient } from "~/components/layout/ThemeAmbient"
import { BloodDrip } from "~/components/landing/HorrorEffects"
import { PromptForm } from "~/components/prompt/PromptForm"
import { AppBrand, AppTagline } from "~/components/shared/AppBrand"
import { LandingHero } from "~/components/landing/LandingHero"
import { LandingFeatures } from "~/components/landing/LandingFeatures"
import { LandingMarquee, LandingCTA } from "~/components/landing/LandingMarquee"

export const Route = createFileRoute("/")({
  component: HomePage,
})

function HomePage() {
  const formRef = useRef<HTMLElement>(null)

  function scrollToForm() {
    formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })
  }

  return (
    <div className="relative dark:bg-[#060508]">
      <div className="ambient-layer" aria-hidden>
        <ThemeAmbient />
      </div>
      <BloodDrip />

      <div className="relative z-10">
        <LandingHero onScrollToForm={scrollToForm} />

        <LandingMarquee />

        <LandingFeatures />

        {/* Summoning chamber */}
        <section
          id="generate"
          ref={formRef}
          className="relative px-4 py-28 sm:py-36 scroll-mt-24 diagonal-section dark:bg-[#070508]"
        >
          <div
            className="absolute inset-0 pointer-events-none opacity-60 dark:opacity-100"
            style={{
              background:
                "radial-gradient(ellipse 50% 40% at 50% 20%, rgba(139,21,56,0.1) 0%, transparent 70%)",
            }}
          />

          <div className="max-w-2xl mx-auto relative">
            <LandingCTA />

            <motion.div
              className="manuscript-card p-6 sm:p-10 relative"
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-60px" }}
              transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }}
            >
              {/* Side margin marks — manuscript */}
              <div className="absolute left-4 top-8 bottom-8 w-px bg-blood-900/15 hidden sm:block" />
              <div className="absolute right-4 top-8 bottom-8 w-px bg-blood-900/15 hidden sm:block" />

              <p className="editorial-label mb-6 text-center sm:text-left">
                The summoning chamber
              </p>

              <div className="relative sm:pl-4">
                <PromptForm />
              </div>
            </motion.div>

            <motion.p
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{ delay: 0.3 }}
              className="mt-10 text-center text-xs text-muted leading-relaxed font-serif italic"
            >
              Horror content generated by AI · Not suitable for all audiences ·{" "}
              <span className="text-blood-800/60 dark:text-blood-700/50 not-italic font-mono text-[10px] tracking-wider">
                Stories are saved to your library
              </span>
            </motion.p>
          </div>
        </section>

        <footer className="relative px-4 py-12 border-t border-blood-900/15 overflow-hidden">
          <div className="manuscript-rule absolute top-0 left-1/2 -translate-x-1/2 w-2/3 max-w-lg" />
          <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 relative pt-4">
            <p className="font-serif text-sm text-muted italic">
              <AppBrand /> — <AppTagline />
            </p>
            <p className="editorial-label !text-[9px] !tracking-[0.4em] opacity-60">
              AI fiction · 16+ · Enter at your own risk
            </p>
          </div>
        </footer>
      </div>
    </div>
  )
}
